In [1]:
from keras.models import Sequential
import numpy as np
from keras.layers.core import Dense
import tensorflow as tf
from sklearn.metrics import confusion_matrix
import pandas as pd
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

In [2]:
conjunto_datos=pd.read_csv('datos_entrada_cinco_o_mas.csv',header=None)
datos_entrada=conjunto_datos.iloc[:,0:7].values
datos_salida=conjunto_datos.iloc[:,7:8].values

In [31]:
modelo=Sequential()
modelo.add(Dense(1,input_dim=7,activation='relu'))
modelo.compile(loss='mean_squared_error',optimizer='adam',metrics=['binary_accuracy'])
modelo.fit(datos_entrada,datos_salida,epochs=300)

Epoch 1/300
1/1 [==============================] - 1s 582ms/step - loss: 0.1656 - binary_accuracy: 0.8000
Epoch 2/300
1/1 [==============================] - 0s 14ms/step - loss: 0.1646 - binary_accuracy: 0.8000
Epoch 3/300
1/1 [==============================] - 0s 5ms/step - loss: 0.1637 - binary_accuracy: 0.8000
Epoch 4/300
1/1 [==============================] - 0s 9ms/step - loss: 0.1628 - binary_accuracy: 0.8000
Epoch 5/300
1/1 [==============================] - 0s 7ms/step - loss: 0.1619 - binary_accuracy: 0.8000
Epoch 6/300
1/1 [==============================] - 0s 10ms/step - loss: 0.1611 - binary_accuracy: 0.8000
Epoch 7/300
1/1 [==============================] - 0s 7ms/step - loss: 0.1604 - binary_accuracy: 0.8000
Epoch 8/300
1/1 [==============================] - 0s 10ms/step - loss: 0.1597 - binary_accuracy: 0.8000
Epoch 9/300
1/1 [==============================] - 0s 4ms/step - loss: 0.1590 - binary_accuracy: 0.8000
Epoch 10/300
1/1 [==============================] - 0s 12ms

1/1 [==============================] - 0s 8ms/step - loss: 0.1288 - binary_accuracy: 0.9000
Epoch 79/300
1/1 [==============================] - 0s 10ms/step - loss: 0.1285 - binary_accuracy: 0.9000
Epoch 80/300
1/1 [==============================] - 0s 7ms/step - loss: 0.1281 - binary_accuracy: 0.9000
Epoch 81/300
1/1 [==============================] - 0s 4ms/step - loss: 0.1277 - binary_accuracy: 0.9000
Epoch 82/300
1/1 [==============================] - 0s 8ms/step - loss: 0.1273 - binary_accuracy: 0.9000
Epoch 83/300
1/1 [==============================] - 0s 7ms/step - loss: 0.1269 - binary_accuracy: 0.9000
Epoch 84/300
1/1 [==============================] - 0s 6ms/step - loss: 0.1265 - binary_accuracy: 0.9000
Epoch 85/300
1/1 [==============================] - 0s 5ms/step - loss: 0.1262 - binary_accuracy: 0.9000
Epoch 86/300
1/1 [==============================] - 0s 4ms/step - loss: 0.1258 - binary_accuracy: 0.9000
Epoch 87/300
1/1 [==============================] - 0s 10ms/step - 

1/1 [==============================] - 0s 5ms/step - loss: 0.1029 - binary_accuracy: 0.9000
Epoch 156/300
1/1 [==============================] - 0s 9ms/step - loss: 0.1026 - binary_accuracy: 0.9000
Epoch 157/300
1/1 [==============================] - 0s 7ms/step - loss: 0.1023 - binary_accuracy: 0.9000
Epoch 158/300
1/1 [==============================] - 0s 4ms/step - loss: 0.1020 - binary_accuracy: 0.9000
Epoch 159/300
1/1 [==============================] - 0s 12ms/step - loss: 0.1018 - binary_accuracy: 0.9000
Epoch 160/300
1/1 [==============================] - 0s 5ms/step - loss: 0.1015 - binary_accuracy: 0.9000
Epoch 161/300
1/1 [==============================] - 0s 6ms/step - loss: 0.1012 - binary_accuracy: 0.9000
Epoch 162/300
1/1 [==============================] - 0s 6ms/step - loss: 0.1009 - binary_accuracy: 0.9000
Epoch 163/300
1/1 [==============================] - 0s 5ms/step - loss: 0.1006 - binary_accuracy: 0.9000
Epoch 164/300
1/1 [==============================] - 0s 12m

1/1 [==============================] - 0s 5ms/step - loss: 0.0845 - binary_accuracy: 0.9000
Epoch 232/300
1/1 [==============================] - 0s 5ms/step - loss: 0.0843 - binary_accuracy: 0.9000
Epoch 233/300
1/1 [==============================] - 0s 7ms/step - loss: 0.0841 - binary_accuracy: 0.9000
Epoch 234/300
1/1 [==============================] - 0s 9ms/step - loss: 0.0839 - binary_accuracy: 0.9000
Epoch 235/300
1/1 [==============================] - 0s 7ms/step - loss: 0.0837 - binary_accuracy: 0.9000
Epoch 236/300
1/1 [==============================] - 0s 6ms/step - loss: 0.0835 - binary_accuracy: 0.9000
Epoch 237/300
1/1 [==============================] - 0s 7ms/step - loss: 0.0833 - binary_accuracy: 0.9000
Epoch 238/300
1/1 [==============================] - 0s 5ms/step - loss: 0.0831 - binary_accuracy: 0.9000
Epoch 239/300
1/1 [==============================] - 0s 13ms/step - loss: 0.0829 - binary_accuracy: 0.9000
Epoch 240/300
1/1 [==============================] - 0s 9ms

In [32]:
pesos,bias=modelo.layers[0].get_weights()
print(pesos)
print(bias)
datos=modelo.evaluate(datos_entrada,datos_salida)
print("\n%s: %.2f%%" %(modelo.metrics[1],datos[1]*100))
y_pred=modelo.predict(datos_entrada).round()
print(y_pred)
y_pred=(y_pred>=.5)
cm=confusion_matrix(datos_salida,y_pred)
print(cm)

[[ 0.91705674]
 [-0.43087938]
 [-0.13947257]
 [-0.7425298 ]
 [ 0.1448692 ]
 [ 0.44019446]
 [ 0.17652252]]
[0.18578137]
1/1 [==============================] - 0s 456ms/step - loss: 0.0726 - binary_accuracy: 1.0000

<keras.metrics.MeanMetricWrapper object at 0x0000021CC30E83A0>: 100.00%
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[5 0]
 [0 5]]
