In [1]:
from keras.models import Sequential
import numpy as np
from keras.layers.core import Dense
import tensorflow as tf
from sklearn.metrics import confusion_matrix
import pandas as pd
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

In [2]:
conjunto_datos=pd.read_csv('datos_entrada_imagenes.csv',header=None)
datos_entrada=conjunto_datos.iloc[:,0:9].values
datos_salida=conjunto_datos.iloc[:,9:10].values

In [24]:
modelo=Sequential()
modelo.add(Dense(1,input_dim=9,activation='relu'))
modelo.compile(loss='mean_squared_error',optimizer='adam',metrics=['binary_accuracy'])
modelo.fit(datos_entrada,datos_salida,epochs=500)

Epoch 1/500
2/2 [==============================] - 0s 2ms/step - loss: 0.4140 - binary_accuracy: 0.5455
Epoch 2/500
2/2 [==============================] - 0s 7ms/step - loss: 0.4018 - binary_accuracy: 0.5455
Epoch 3/500
2/2 [==============================] - 0s 3ms/step - loss: 0.3907 - binary_accuracy: 0.5455
Epoch 4/500
2/2 [==============================] - 0s 7ms/step - loss: 0.3801 - binary_accuracy: 0.5758
Epoch 5/500
2/2 [==============================] - 0s 3ms/step - loss: 0.3700 - binary_accuracy: 0.5758
Epoch 6/500
2/2 [==============================] - 0s 3ms/step - loss: 0.3608 - binary_accuracy: 0.5758
Epoch 7/500
2/2 [==============================] - 0s 4ms/step - loss: 0.3520 - binary_accuracy: 0.5758
Epoch 8/500
2/2 [==============================] - 0s 3ms/step - loss: 0.3434 - binary_accuracy: 0.5758
Epoch 9/500
2/2 [==============================] - 0s 5ms/step - loss: 0.3347 - binary_accuracy: 0.5758
Epoch 10/500
2/2 [==============================] - 0s 3ms/step 

2/2 [==============================] - 0s 2ms/step - loss: 0.0852 - binary_accuracy: 0.9091
Epoch 80/500
2/2 [==============================] - 0s 7ms/step - loss: 0.0844 - binary_accuracy: 0.9091
Epoch 81/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0835 - binary_accuracy: 0.9091
Epoch 82/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0827 - binary_accuracy: 0.9091
Epoch 83/500
2/2 [==============================] - 0s 8ms/step - loss: 0.0819 - binary_accuracy: 0.9091
Epoch 84/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0809 - binary_accuracy: 0.9091
Epoch 85/500
2/2 [==============================] - 0s 5ms/step - loss: 0.0800 - binary_accuracy: 0.9091
Epoch 86/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0792 - binary_accuracy: 0.9091
Epoch 87/500
2/2 [==============================] - 0s 5ms/step - loss: 0.0785 - binary_accuracy: 0.9091
Epoch 88/500
2/2 [==============================] - 0s 2ms/step - lo

2/2 [==============================] - 0s 4ms/step - loss: 0.0540 - binary_accuracy: 0.9091
Epoch 157/500
2/2 [==============================] - 0s 6ms/step - loss: 0.0538 - binary_accuracy: 0.9091
Epoch 158/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0537 - binary_accuracy: 0.9091
Epoch 159/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0536 - binary_accuracy: 0.9091
Epoch 160/500
2/2 [==============================] - 0s 7ms/step - loss: 0.0536 - binary_accuracy: 0.9091
Epoch 161/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0536 - binary_accuracy: 0.9091
Epoch 162/500
2/2 [==============================] - 0s 6ms/step - loss: 0.0535 - binary_accuracy: 0.9091
Epoch 163/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0533 - binary_accuracy: 0.9091
Epoch 164/500
2/2 [==============================] - 0s 6ms/step - loss: 0.0532 - binary_accuracy: 0.9091
Epoch 165/500
2/2 [==============================] - 0s 3ms/

2/2 [==============================] - 0s 6ms/step - loss: 0.0479 - binary_accuracy: 0.9091
Epoch 234/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0478 - binary_accuracy: 0.9091
Epoch 235/500
2/2 [==============================] - 0s 6ms/step - loss: 0.0478 - binary_accuracy: 0.9091
Epoch 236/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0478 - binary_accuracy: 0.9091
Epoch 237/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0477 - binary_accuracy: 0.9091
Epoch 238/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0476 - binary_accuracy: 0.9091
Epoch 239/500
2/2 [==============================] - 0s 5ms/step - loss: 0.0476 - binary_accuracy: 0.9091
Epoch 240/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0474 - binary_accuracy: 0.9091
Epoch 241/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0473 - binary_accuracy: 0.9091
Epoch 242/500
2/2 [==============================] - 0s 5ms/

2/2 [==============================] - 0s 6ms/step - loss: 0.0434 - binary_accuracy: 0.9394
Epoch 311/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0434 - binary_accuracy: 0.9394
Epoch 312/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0433 - binary_accuracy: 0.9394
Epoch 313/500
2/2 [==============================] - 0s 6ms/step - loss: 0.0433 - binary_accuracy: 0.9394
Epoch 314/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0433 - binary_accuracy: 0.9394
Epoch 315/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0432 - binary_accuracy: 0.9394
Epoch 316/500
2/2 [==============================] - 0s 7ms/step - loss: 0.0432 - binary_accuracy: 0.9394
Epoch 317/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0432 - binary_accuracy: 0.9394
Epoch 318/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0432 - binary_accuracy: 0.9394
Epoch 319/500
2/2 [==============================] - 0s 3ms/

2/2 [==============================] - 0s 4ms/step - loss: 0.0392 - binary_accuracy: 0.9697
Epoch 387/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0393 - binary_accuracy: 0.9697
Epoch 388/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0394 - binary_accuracy: 0.9697
Epoch 389/500
2/2 [==============================] - 0s 13ms/step - loss: 0.0394 - binary_accuracy: 0.9697
Epoch 390/500
2/2 [==============================] - 0s 7ms/step - loss: 0.0394 - binary_accuracy: 0.9697
Epoch 391/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0394 - binary_accuracy: 0.9697
Epoch 392/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0394 - binary_accuracy: 0.9697
Epoch 393/500
2/2 [==============================] - 0s 8ms/step - loss: 0.0395 - binary_accuracy: 0.9697
Epoch 394/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0395 - binary_accuracy: 0.9697
Epoch 395/500
2/2 [==============================] - 0s 5ms

2/2 [==============================] - 0s 7ms/step - loss: 0.0351 - binary_accuracy: 0.9394
Epoch 463/500
2/2 [==============================] - 0s 5ms/step - loss: 0.0350 - binary_accuracy: 0.9394
Epoch 464/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0350 - binary_accuracy: 0.9394
Epoch 465/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0350 - binary_accuracy: 0.9394
Epoch 466/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0350 - binary_accuracy: 0.9394
Epoch 467/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0350 - binary_accuracy: 0.9697
Epoch 468/500
2/2 [==============================] - 0s 7ms/step - loss: 0.0350 - binary_accuracy: 0.9697
Epoch 469/500
2/2 [==============================] - 0s 3ms/step - loss: 0.0350 - binary_accuracy: 0.9697
Epoch 470/500
2/2 [==============================] - 0s 4ms/step - loss: 0.0350 - binary_accuracy: 0.9697
Epoch 471/500
2/2 [==============================] - 0s 3ms/

In [25]:
pesos,bias=modelo.layers[0].get_weights()
print(pesos)
print(bias)
datos=modelo.evaluate(datos_entrada,datos_salida)
print("\n%s: %.2f%%" %(modelo.metrics[1],datos[1]*100))
y_pred=modelo.predict(datos_entrada).round()
print(y_pred)
y_pred=(y_pred>=.5)
cm=confusion_matrix(datos_salida,y_pred)
print(cm)

[[-0.31944644]
 [ 0.3784378 ]
 [ 0.38180202]
 [-0.6585359 ]
 [ 0.09756556]
 [ 0.2911367 ]
 [-0.15068644]
 [-0.00375576]
 [ 0.14106189]]
[-0.14845273]
2/2 [==============================] - 0s 2ms/step - loss: 0.0349 - binary_accuracy: 1.0000

<keras.metrics.MeanMetricWrapper object at 0x000002503952CA30>: 100.00%
[[1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[30  0]
 [ 0  3]]
